CREATE DATABASE IF NOT EXISTS BLOCOSRAPIDOS;
USE BLOCOSRAPIDOS;

CREATE TABLE IF NOT EXISTS NOTAS(
    ID_NOTAS INT AUTO_INCREMENT PRIMARY KEY,
    TITULO_NOTAS VARCHAR(30) NOT NULL,
    CONTEUDO_NOTAS VARCHAR(1000) NULL,
    DATA_NOTA  DATETIME DEFAULT CURRENT_TIMESTAMP
);